name: Terraform CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" > tfplan.txt

      - name: Comment Plan on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: tfplan.txt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
