name: Terraform CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" > tfplan.txt
          # Save plan output to an output variable, escaping newlines
          plan_output=$(cat tfplan.txt | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')
          echo "::set-output name=plan-output::$plan_output"

      - name: Comment Plan on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Terraform Plan Output
            ```
            ${{ steps.plan.outputs.plan-output }}
            ```

      - name: Send Terraform Plan to Microsoft Teams
        run: |
          raw_output="${{ steps.plan.outputs.plan-output }}"
          escaped_output=$(echo "$raw_output" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')

          curl -X POST ${{ secrets.MS_TEAMS_API }} \
            -H "Content-Type: application/json" \
            -d "{
              \"@type\": \"MessageCard\",
              \"@context\": \"https://schema.org/extensions\",
              \"themeColor\": \"00BFFF\",
              \"summary\": \"Terraform Plan Notification\",
              \"title\": \"Terraform Plan Details\",
              \"sections\": [
                {
                  \"activityTitle\": \"**${{ github.actor }}** created a Pull Request\",
                  \"activitySubtitle\": \"Date: $(date -u -d '+5 hour 30 min' +'%Y-%m-%d %H:%M IST')\",
                  \"facts\": [
                    { \"name\": \"Branch\", \"value\": \"\`${{ github.head_ref || github.ref_name }}\`\" },
                    { \"name\": \"Repository\", \"value\": \"[${{ github.repository }}](https://github.com/${{ github.repository }})\" },
                    { \"name\": \"Pull Request\", \"value\": \"[PR #${{ github.event.pull_request.number }}](https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }})\" }
                  ],
                  \"markdown\": true
                },
                {
                  \"title\": \"Terraform Plan Output\",
                  \"text\": \"\`\`\`\n${escaped_output}\n\`\`\`\"
                }
              ],
              \"potentialAction\": [
                {
                  \"@type\": \"OpenUri\",
                  \"name\": \"View Pull Request\",
                  \"targets\": [
                    { \"os\": \"default\", \"uri\": \"https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}\" }
                  ]
                }
              ]
            }"

      - name: Remove tfplan file
        run: rm tfplan.txt
