name: Terraform CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" > tfplan.txt

          # Save output for use in other steps (multi-line output via GITHUB_ENV)
          echo "PLAN_OUTPUT<<EOF" >> $GITHUB_ENV
          cat tfplan.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment Plan on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Terraform Plan Output
            ```terraform
            ${{ env.PLAN_OUTPUT }}
            ```

      - name: Send Terraform Plan to Microsoft Teams
        env:
          PLAN_OUTPUT: ${{ env.PLAN_OUTPUT }}
        run: |
          # Escape JSON-sensitive characters
          ESCAPED_PLAN=$(echo "$PLAN_OUTPUT" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')

          curl -X POST ${{ secrets.MS_TEAMS_API }} \
            -H "Content-Type: application/json" \
            -d "{
              \"@type\": \"MessageCard\",
              \"@context\": \"https://schema.org/extensions\",
              \"themeColor\": \"00BFFF\",
              \"summary\": \"Terraform Plan Notification\",
              \"title\": \"Terraform Plan Executed Successfully\",
              \"sections\": [
                {
                  \"activityTitle\": \"**${{ github.actor }}** created a Pull Request\",
                  \"activitySubtitle\": \"Date: $(date -u +'%Y-%m-%d %H:%M UTC')\",
                  \"facts\": [
                    { \"name\": \"Branch\", \"value\": \"\`${{ github.head_ref || github.ref_name }}\`\" },
                    { \"name\": \"Repository\", \"value\": \"[${{ github.repository }}](https://github.com/${{ github.repository }})\" },
                    { \"name\": \"Pull Request\", \"value\": \"[PR #${{ github.event.pull_request.number }}](https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }})\" }
                  ],
                  \"markdown\": true
                },
                {
                  \"title\": \"Terraform Plan Output\",
                  \"text\": \"\`\`\`\n${ESCAPED_PLAN}\n\`\`\`\"
                }
              ],
              \"potentialAction\": [
                {
                  \"@type\": \"OpenUri\",
                  \"name\": \"View Pull Request\",
                  \"targets\": [
                    { \"os\": \"default\", \"uri\": \"https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}\" }
                  ]
                }
              ]
            }"

      - name: Cleanup
        run: rm -f tfplan.txt
